---
- hosts: setup
  gather_facts: False
  vars:
    imgfile: cirros-0.3.1-x86_64-disk.img
    cirros_url: http://download.cirros-cloud.net/0.3.1/$imgfile
  
  tasks:

  - name: create external gateway for router
    quantum_router_gateway: router_name="$setup_router_name"
                            network_name="$setup_external_network_name"
                            login_tenant_name="$setup_tenant" 
                            login_username=admin 
                            login_password="$setup_admin_password" 
                            auth_url="http://${keystone_endpoint_host}:35357/v2.0/"
                            state=absent

  - name: create internal interface for router
    quantum_router_interface: router_name="$setup_router_name"
                              subnet_name="$setup_internal_network_subnet_name"
                              login_tenant_name="$setup_tenant" 
                              login_username=admin 
                              login_password="$setup_admin_password" 
                              auth_url="http://${keystone_endpoint_host}:35357/v2.0/"
                              state=absent 

  - name: create router
    quantum_router: name="$setup_router_name"
                    login_tenant_name="$setup_tenant" 
                    login_username=admin 
                    login_password="$setup_admin_password" 
                    auth_url="http://${keystone_endpoint_host}:35357/v2.0/"
                    state=absent 
    register: router

  - name: create the subnet for external network
    quantum_subnet: name="$setup_external_network_subnet_name" 
                    network_name="$setup_external_network_name"
                    cidr="$setup_external_network_subnet_cidr"
                    enable_dhcp=false
                    gateway_ip="$setup_external_network_subnet_gateway_ip"
                    allocation_pool_start="$setup_external_network_subnet_allocation_pool_start"
                    allocation_pool_end="$setup_external_network_subnet_allocation_pool_end"
                    login_tenant_name="$setup_tenant" 
                    login_username=admin 
                    login_password="$setup_admin_password" 
                    auth_url="http://${keystone_endpoint_host}:35357/v2.0/"
                    state=absent

  - name: create the external network
    quantum_network: name="$setup_external_network_name" 
                     router_external=True
                     login_tenant_name="$setup_tenant" 
                     login_username=admin 
                     login_password="$setup_admin_password" 
                     auth_url="http://${keystone_endpoint_host}:35357/v2.0/"
                     state=absent
    register: network

  - name: create the subnet for internal network
    quantum_subnet: name="$setup_internal_network_subnet_name" 
                    network_name="$setup_internal_network_name"
                    cidr="$setup_internal_network_subnet_cidr"
                    enable_dhcp=true
                    gateway_ip="$setup_internal_network_subnet_gateway_ip"
                    login_tenant_name="$setup_tenant" 
                    login_username=admin 
                    login_password="$setup_admin_password" 
                    auth_url="http://${keystone_endpoint_host}:35357/v2.0/"
                    state=absent

  - name: create the internal network
    quantum_network: name="$setup_internal_network_name" 
                     provider_network_type=gre
                     provider_segmentation_id=5
                     login_tenant_name="$setup_tenant" 
                     login_username=admin 
                     login_password="$setup_admin_password" 
                     auth_url="http://${keystone_endpoint_host}:35357/v2.0/"
                     state=absent
    register: network
