---
- name: Install and configure openvswitch and quantum agent
  hosts: quantum:compute
  sudo: True
  gather_facts: True
  tasks:

    - name: enable net.ipv4.ip_forward in sysctl
      sysctl: name=net.ipv4.ip_forward value=1 state=present

    - name: enable net.ipv4.conf.all.forwarding in sysctl
      sysctl: name=net.ipv4.conf.all.forwarding value=1 state=present

    - name: ensure openvswitch packages are installed
      apt: pkg="{{ item }}" state=latest update_cache=yes cache_valid_time=600
      with_items:
        - openvswitch-common
        - openvswitch-switch
        - quantum-plugin-openvswitch-agent
      
    - name: ensure services are stopped
      service: name="{{ item }}" state=stopped
      with_items:
        - quantum-plugin-openvswitch-agent
        - openvswitch-switch

    - name: ensure quantum sqlite is deleted
      file: dest=/var/lib/quantum/quantum.sqlite state=absent

    - name: update quantum.conf from template
      template: src=templates/etc/quantum/quantum.conf 
                dest=/etc/quantum/quantum.conf 
                owner=quantum group=quantum mode=0600

    - name: update ovs_quantum_plugin.ini from template
      template: src=templates/etc/quantum/plugins/openvswitch/ovs_quantum_plugin.ini 
                dest=/etc/quantum/plugins/openvswitch/ovs_quantum_plugin.ini 
                owner=quantum group=quantum mode=0600

    - name: make sure symlink to ovs_quantum_plugin.ini exists
      file: src=/etc/quantum/plugins/openvswitch/ovs_quantum_plugin.ini 
            dest=/etc/quantum/plugin.ini 
            state=link

    - name: ensure OVS kernel module is loaded
      action: command /sbin/modprobe openvswitch_mod
      ignore_errors: True
      register: modprobe_result

    - name: ensure packages to build openvswitch module are installed
      apt: pkg="{{ item }}" state=latest update_cache=yes cache_valid_time=600
      with_items:
        - build-essential
        - dkms
        - openvswitch-datapath-dkms
        - openvswitch-datapath-source
      when: modprobe_result|failed

    - name: build openvswitch-datapath kernel module - this may take a while
      action: command /usr/bin/module-assistant -i auto-install openvswitch-datapath
      when: modprobe_result|failed

    - name: ensure openvswitch-switch is started and enabled
      service: name=openvswitch-switch state=started enabled=yes

    - name: ensure ovs internal bridge is present
      command: /usr/bin/ovs-vsctl -- --may-exist add-br br-int

    - name: ensure quantum openvswitch service is started and enabled
      service: name=quantum-plugin-openvswitch-agent state=started enabled=yes
