---
- name: Install quantum-api server
  hosts: quantum-api
  sudo: True
  gather_facts: True
  tasks:

    - name: ensure quantum-api packages are installed
      apt: pkg=quantum-server state=latest update_cache=yes cache_valid_time=600

    - name: ensure services are stopped
      service: name=quantum-server state=stopped

    - name: ensure quantum sqlite is deleted
      file: dest=/var/lib/quantum/quantum.sqlite state=absent

    - name: update quantum.conf from template
      template: src=templates/etc/quantum/quantum.conf 
                dest=/etc/quantum/quantum.conf 
                owner=quantum group=quantum mode=0600

    - name: ensure quantum-api services are started and enabled
      service: name=quantum-server state=started enabled=yes

    - name: create quantum service user
      keystone_user: endpoint="http://{{ keystone_endpoint_host }}:35357/v2.0/"
                     token="{{ keystone_admin_token }}" 
                     tenant=service 
                     user=quantum 
                     password="{{ quantum_identity_password }}"

    - name: add quantum service user to the service tenant with the admin role
      keystone_user: endpoint="http://{{ keystone_endpoint_host }}:35357/v2.0/"
                     token="{{ keystone_admin_token }}" 
                     tenant=service 
                     user=quantum 
                     role=admin

    - name: add quantum endpoint to keystone
      keystone_service: endpoint="http://{{ keystone_endpoint_host }}:35357/v2.0/"
                        token="{{ keystone_admin_token }}" 
                        region="{{ keystone_default_region }}"
                        name=quantum
                        type=network
                        description="Networking Service"
                        public_url="http://{{ quantum_endpoint_host }}:9696"
                        internal_url="http://{{ quantum_endpoint_host }}:9696"
                        admin_url="http://{{ quantum_endpoint_host }}:9696"

