---
- hosts: quantum-api
  sudo: True
  tasks:

  - name: ensure quantum-api packages are installed
    apt: pkg=quantum-server state=latest

  - name: ensure services are stopped
    service: name=quantum-server state=stopped

  - name: ensure quantum sqlite is deleted
    file: dest=/var/lib/quantum/quantum.sqlite state=absent

  - name: update quantum.conf from template
    template: src=templates/etc/quantum/quantum.conf dest=/etc/quantum/quantum.conf owner=quantum group=quantum mode=0600

  - name: update ovs_quantum_plugin.ini from template
    template: src=templates/etc/quantum/plugins/openvswitch/ovs_quantum_plugin.ini dest=/etc/quantum/plugins/openvswitch/ovs_quantum_plugin.ini owner=quantum group=quantum mode=0600

  - name: make sure symlink to ovs_quantum_plugin.ini exists
    file: src=/etc/quantum/plugins/openvswitch/ovs_quantum_plugin.ini dest=/etc/quantum/plugin.ini state=link

  - name: ensure services are started
    service: name=quantum-server state=started

  - name: create quantum service user
    keystone_user: token="$keystone_admin_token" user=quantum tenant=service password="$quantum_identity_password"

  - name: add quantum service user to the service tenant with the admin role
    keystone_user: token="$keystone_admin_token" tenant=service user=quantum role=admin

  - name: add services
    keystone_service: >
          token="$keystone_admin_token"
          region="$keystone_default_region"
          name=quantum
          type=network
          description="Networking Service"
          public_url="http://${quantum_endpoint_host}:9696"
          internal_url="http://${quantum_endpoint_host}:9696"
          admin_url="http://${quantum_endpoint_host}:9696"

