---
- name: Install keystone
  hosts: keystone
  sudo: True
  gather_facts: False
  tasks:

  - name: ensure keystone packages are installed
    apt: pkg=$item state=latest
    with_items:
      - ntp
      - keystone
      - python-keystone
      - python-keystoneclient

  - name: ensure keystone is stopped
    service: name=keystone state=stopped

  - name: ensure sqlite keystone database is deleted
    file: dest=/var/lib/keystone/keystone.db state=absent

  - name: ensure keystone config script is present
    template: >
          src=templates/etc/keystone/keystone.conf
          dest=/etc/keystone/keystone.conf
          owner=keystone
          group=keystone
          mode=0600

  - name: initialize keystone database
    keystone_manage: action=db_sync

  - name: ensure keystone is started
    service: name=keystone state=started

    # keystone seems to take a while...
  - name: wait for keystone to come back up
    wait_for: port=35357 

  - name: create service tenant
    keystone_user: token="$keystone_admin_token" tenant=service tenant_description="Service Tenant"

  - name: add keystone endpoint information
    keystone_service: >
          token="$keystone_admin_token"
          region="$keystone_default_region"
          name=keystone
          type=identity
          description="Identity Service"
          public_url="http://${keystone_endpoint_host}:5000/v2.0"
          internal_url="http://${keystone_endpoint_host}:5000/v2.0"
          admin_url="http://${keystone_endpoint_host}:35357/v2.0"
