---
- name: gather required facts
  hosts: mysql:rabbitmq:keystone:glance:quantum-api

- name: Install nova
  hosts: nova
  sudo: True
  gather_facts: True
  tasks:

    - name: ensure nova packages are installed
      apt: pkg="{{ item }}" state=latest update_cache=yes cache_valid_time=600
      with_items:
        - nova-api
        - nova-cert
        - nova-common
        - nova-conductor
        - nova-scheduler
        - python-nova
        - python-novaclient
        - nova-consoleauth
        - novnc
        - nova-novncproxy

    - name: ensure services are stopped
      service: name="{{ item }}" state=stopped
      with_items:
        - nova-api
        - nova-cert
        - nova-conductor
        - nova-consoleauth
        - nova-scheduler
        - nova-novncproxy

    - name: ensure nova sqlite is deleted
      file: dest=/var/lib/nova/nova.sqlite state=absent

    - name: update nova.conf from template
      template: src=templates/etc/nova/nova.conf 
                dest=/etc/nova/nova.conf 
                owner=nova group=nova mode=0600

    - name: update api-paste.ini from template
      template: src=templates/etc/nova/api-paste.ini 
                dest=/etc/nova/api-paste.ini 
                owner=nova group=nova mode=0600

    - name: ensure database is synced
      command: /usr/bin/nova-manage db sync

    - name: ensure services are started
      service: name="{{ item }}" state=started enabled=yes
      with_items:
        - nova-api
        - nova-cert
        - nova-conductor
        - nova-consoleauth
        - nova-scheduler
        - nova-novncproxy

    - name: create nova user in keystone
      keystone_user: endpoint="{{ keystone_admin_url }}"
                     token="{{ keystone_admin_token }}" 
                     tenant=service 
                     user=nova 
                     password="{{ nova_identity_password }}"

    - name: add nova user to the service tenant with the admin role
      keystone_user: endpoint="{{ keystone_admin_url }}"
                     token="{{ keystone_admin_token }}" 
                     tenant=service 
                     user=nova 
                     role=admin

    - name: add nova endpoint
      keystone_service: endpoint="{{ keystone_admin_url }}"
                        token="{{ keystone_admin_token }}"
                        region="{{ default_region }}"
                        name=nova
                        type=compute
                        description="Compute Service"
                        public_url="{{ nova_public_url }}"
                        internal_url="{{ nova_internal_url }}"
                        admin_url="{{ nova_admin_url }}"

    - name: add ec2 compatibility layer endpoint
      keystone_service: endpoint="{{ keystone_admin_url }}"
                        token="{{ keystone_admin_token }}"
                        region="{{ default_region }}"
                        name=ec2
                        type=ec2
                        description="EC2 Compatibility Layer"
                        public_url="{{ ec2_public_url }}"
                        internal_url="{{ ec2_internal_url }}"
                        admin_url="{{ ec2_admin_url }}"

