---
- hosts: compute
  user: vagrant
  sudo: True
  vars_files:
    - ../global_vars.yaml

  handlers:
  - include: handlers.yaml

  tasks:
  - name: ensure apt repo is up to date
    action: apt update-cache=yes

  # http://docs.openstack.org/essex/openstack-compute/install/apt/content/installing-ntp.html
  - name: cron job to sync time hourly
    action: template src=templates/timesync dest=/etc/cron.hourly owner=root group=root mode=0755

    # http://docs.openstack.org/essex/openstack-compute/install/apt/content/compute-configuring-guest-network.html
  - include: tasks/bridge.yaml

#  - name: ensure $item is installed
#    action: apt pkg=$item
#    with_items:
#      - 