---
- hosts: controller
  user: vagrant
  sudo: True
  vars_files:
    - ../global_vars.yaml

  tasks:

    # http://docs.openstack.org/essex/openstack-compute/install/apt/content/compute-configuring-guest-network.html
  - include: tasks/bridge.yaml

  - name: ensure nova database is present
    action: mysql_db name=nova

  # http://docs.openstack.org/essex/openstack-compute/install/apt/content/setting-up-sql-database-mysql.html
  - name: ensure nova database user is present
    action: mysql_user name=nova password=$nova_db_password priv=nova.*:ALL

  - name: ensure nova packages are installed
    action: apt pkg=$item
    with_items:
      - rabbitmq-server
      - nova-compute
      - nova-volume
      - nova-vncproxy
      - nova-api
      - nova-ajax-console-proxy
      - nova-cert
      - nova-consoleauth
      - nova-doc
      - nova-scheduler
      - nova-network


  # http://docs.openstack.org/trunk/openstack-compute/install/apt/content/compute-minimum-configuration-settings.html
  - name: ensure nova.conf file is present
  - action: template src=templates/nova.conf  dest=/etc/nova/nova.conf owner=nova group=nova mode=0640

  - name: ensure services are stopped
    action: service name=$item state=stopped
    with_items:
      - nova-api
      - nova-compute
      - nova-network
      - nova-scheduler
      - nova-vncproxy
      - nova-volume


  handlers:
  - include: handlers.yaml
