---
- hosts: controller
  user: vagrant
  sudo: True
  vars_files:
    - ../global_vars.yaml

  tasks:

  - name: ensure nova database is present
    action: mysql_db name=nova

  # http://docs.openstack.org/essex/openstack-compute/install/apt/content/setting-up-sql-database-mysql.html
  - name: ensure nova database user is present
    action: mysql_user name=nova host=% password=$nova_db_password priv=nova.*:ALL

  - name: ensure eth2 is in promiscuous mode
    action: command /sbin/ifconfig eth2 promisc

  - name: ensure nova packages are installed
    action: apt pkg=$item
    with_items:
      - rabbitmq-server
      - nova-vncproxy
      - nova-api
      - nova-ajax-console-proxy
      - nova-cert
      - nova-consoleauth
      - nova-doc
      - nova-scheduler
      - nova-network
      - bridge-utils


  # http://docs.openstack.org/trunk/openstack-compute/install/apt/content/compute-minimum-configuration-settings.html
  - name: ensure nova.conf file is present
    action: template src=templates/nova.conf dest=/etc/nova/nova.conf owner=nova group=nova mode=0640

  - name: ensure services are stopped
    action: service name=$item state=stopped
    with_items:
      - nova-api
      - nova-network
      - nova-scheduler
      - nova-vncproxy

  - name: ensure api-paste.ini is present
    action: template src=templates/api-paste.ini dest=/etc/nova/api-paste.ini owner=nova group=nova mode=0600

  # http://docs.openstack.org/essex/openstack-compute/install/apt/content/compute-db-sync.html
  - name: ensure database is synced
    action: command /usr/bin/nova-manage db sync
  - name: ensure services are started
    action: service name=$item state=started
    with_items:
      - nova-api
      - nova-network
      - nova-scheduler
      - nova-vncproxy
      - nova-consoleauth
      - nova-cert
      - rabbitmq-server

  # http://docs.openstack.org/essex/openstack-compute/install/apt/content/compute-create-network.html
  - name: ensure network has been created
    action: shell /usr/bin/nova-manage network create private --fixed_range_v4=192.168.100.0/24 --bridge_interface=br100 --num_networks=1 --network_size=256 || true
