---
- hosts: compute
  user: vagrant
  sudo: True
  vars_files:
    - ../global_vars.yaml

  handlers:
  - name: restart networking
    action: service name=networking state=restarted

  tasks:
  - name: ensure apt repo is up to date
    action: apt update-cache=yes

  # http://docs.openstack.org/essex/openstack-compute/install/apt/content/installing-ntp.html
  - name: cron job to sync time hourly
    action: template src=templates/timesync dest=/etc/cron.hourly owner=root group=root mode=0755

  # http://docs.openstack.org/essex/openstack-compute/install/apt/content/compute-configuring-guest-network.html
  - name: ensure bridge-utils are installed
    action: apt pkg=bridge-utils

  - name: ensure interfaces file has bridge info
    action: template src=templates/interfaces dest=/etc/network/interfaces owner=root group=root mode=0644
    notify:
      - restart networking

  - name: ensure bridge is present
    action: command /sbin/brctl addbr br100
    notify:
      - restart networking

#  - name: ensure $item is installed
#    action: apt pkg=$item
#    with_items:
#      - 