---
- name: gather keystone host facts
  hosts: keystone
  gather_facts: True

- name: Configure Swift Node
  hosts: swift
  sudo: True
  gather_facts: True
  tasks:

    - name: ensure required base packages are present
      apt: 
        pkg: "{{ item }}" 
        state: latest 
        update_cache: yes 
        cache_valid_time: 600
      with_items:
        - memcached
        - python-webob
        - rsync
        - swift
        - swift-account
        - swift-container
        - swift-object
        - swift-proxy
        - xfsprogs

    - name: ensure services are stopped
      service: 
        name: "{{ item }}" 
        state: stopped
      with_items:
        - memcached
        - rsync
        - swift-account
        - swift-account-auditor
        - swift-account-reaper
        - swift-account-replicator
        - swift-container
        - swift-container-auditor
        - swift-container-replicator
        - swift-container-updater
        - swift-object
        - swift-object-auditor
        - swift-object-replicator
        - swift-object-updater
        - swift-proxy

    - name: create /etc/swift directory if not already there
      file:
        path: /etc/swift
        owner: swift
        group: swift
        mode: 0750
        state: directory

    - name: update swift.conf from template
      template: 
        src: templates/etc/swift/swift.conf 
        dest: /etc/swift/swift.conf 
        owner: swift 
        group: swift 
        mode: 0600

    - name: update account-server.conf from template
      template: 
        src: templates/etc/swift/account-server.conf 
        dest: /etc/swift/account-server.conf 
        owner: swift 
        group: swift 
        mode: 0600

    - name: update container-server.conf from template
      template: 
        src: templates/etc/swift/container-server.conf 
        dest: /etc/swift/container-server.conf 
        owner: swift 
        group: swift 
        mode: 0600

    - name: update object-server.conf from template
      template: 
        src: templates/etc/swift/object-server.conf 
        dest: /etc/swift/object-server.conf 
        owner: swift 
        group: swift 
        mode: 0600

    - name: update proxy-server.conf from template
      template:
        src: templates/etc/swift/proxy-server.conf
        dest: /etc/swift/proxy-server.conf
        owner: swift
        group: swift
        mode: 0600

    - name: update memcached.conf from template
      template:
        src: templates/etc/memcached.conf
        dest: /etc/memcached.conf
        owner: root
        group: root
        mode: 0644

    - name: update rsyncd.conf from template
      template: 
        src: templates/etc/rsyncd.conf 
        dest: /etc/rsyncd.conf 
        owner: root 
        group: root 
        mode: 0644

    - name: create /var/lib/swift directory if not already there
      file:
        path: /var/lib/swift
        owner: swift
        group: swift
        mode: 0750
        state: directory

    - name: create /var/lib/swift/keystone-signing directory if not already there
      file:
        path: /var/lib/swift/keystone-signing
        owner: swift
        group: swift
        mode: 0750
        state: directory

    - name: create filesystems on devices
      command: mkfs.xfs -i size=1024 /dev/{{ item }}
      ignore_errors: yes
      with_items: swift_storage_devices

    - name: create device directories
      file:
        path: /srv/node/{{ item }}
        owner: swift
        group: swift
        mode: 0750
        state: directory
      with_items: swift_storage_devices

    - name: mount device directories
      mount: 
        name: /srv/node/{{ item }} 
        src: /dev/{{ item }} 
        fstype: xfs 
        opts: noatime,nodiratime,nobarrier,logbufs=8
        state: mounted
      with_items: swift_storage_devices

    - name: create proxy self-signed certificate
      command: 
        free_form: openssl req -new nodes -x509 -subj "/CN=swift-internal" -days 3650 -out /etc/swift/cert.crt -keyout /etc/swift/cert.key
        creates: /etc/swift/cert.crt

    #- name: create builders
    
    #- name: create rings
    
    #- name: fix /etc/swift permissions and ownership?

    - name: ensure services are started
      service: 
        name: "{{ item }}" 
        state: started 
        enabled: yes
      with_items:
        - memcached
        - rsync
        - swift-account
        - swift-account-auditor
        - swift-account-reaper
        - swift-account-replicator
        - swift-container
        - swift-container-auditor
        - swift-container-replicator
        - swift-container-updater
        - swift-object
        - swift-object-auditor
        - swift-object-replicator
        - swift-object-updater
        - swift-proxy
