---
- name: Install Swift Account Server
  hosts: swift-node
  sudo: True
  gather_facts: True
  tasks:

    - name: ensure required base packages are present
      apt: pkg="{{ item }}" state=latest update_cache=yes cache_valid_time=600
      with_items:
        - swift-account
        - swift-container
        - swift-object
        - xfsprogs

    - name: ensure services are stopped
      service: name="{{ item }}" state=stopped
      with_items:
        - rsync

    - name: ensure services are started
      service: name="{{ item }}" state=started enabled=yes
      with_items:
        - rsync
