---
- name: configure frontend system
  hosts: frontend
  sudo: False
  gather_facts: True
  tasks:

    - name: ensure clients are installed
      apt: pkg="{{ item }}" state=latest update_cache=yes cache_valid_time=600
      sudo: True
      with_items:
        - python-keystoneclient
        - python-swiftclient
        - python-glanceclient
        - python-quantumclient
        - python-cinderclient
        - python-novaclient

    - name: create tenant
      keystone_user: endpoint="http://{{ keystone_endpoint_host }}:35357/v2.0/"
                     token="{{ keystone_admin_token }}" 
                     tenant="{{ tenant }}" 
                     tenant_description="{{ tenant }}"

    - name: create admin user
      keystone_user: endpoint="http://{{ keystone_endpoint_host }}:35357/v2.0/"
                     token="{{ keystone_admin_token }}" 
                     tenant="{{ tenant }}" 
                     user=admin 
                     password="{{ admin_password }}"

    - name: create admin role and associate it with admin user
      keystone_user: endpoint="http://{{ keystone_endpoint_host }}:35357/v2.0/"
                     token="{{ keystone_admin_token }}" 
                     tenant="{{ tenant }}" 
                     user=admin 
                     role=admin

    - name: update openrc template
      template: src=templates/openrc 
                dest={{ ansible_env['HOME'] }}/openrc 
                mode=0600

    - name: update admin.openrc template
      template: src=templates/admin.openrc 
                dest={{ ansible_env['HOME'] }}/admin.openrc 
                mode=0600
