---
- hosts: controller
  user: vagrant
  sudo: True
  vars_files:
    - ../global_vars.yaml

  handlers:
  - name: restart networking
    action: service name=networking state=restarted

  # http://docs.openstack.org/essex/openstack-compute/install/apt/content/compute-configuring-guest-network.html
  - name: ensure bridge-utils are installed
    action: apt pkg=bridge-utils

  - name: ensure interfaces file has bridge info
    action: template src=templates/interfaces dest=/etc/network/interfaces owner=root group=root mode=0644
    notify:
      - restart networking

  - name: ensure bridge is present
    action: command /sbin/brctl addbr br100
    notify:
      - restart networking

  - name: ensure nova database is present
    action: mysql_db name=nova

  # http://docs.openstack.org/essex/openstack-compute/install/apt/content/setting-up-sql-database-mysql.html
  - name: ensure nova database user is present
    action: mysql_user name=nova password=$nova_db_password priv=nova.*:ALL

#  - name: ensure $item is installed
#    action: apt pkg=$item
#    with_items:
#      - 
