---
- name: Setup steps that are not specific to a particular OpenStack project
  hosts: cloud
  sudo: True
  gather_facts: False
  tasks:

    - name: update apt cache
      apt: update_cache=yes

      # This is necessary to use the apt_repository module
    - name: ensure add-apt-repository, ubuntu-cloud-keyring and ntp are present
      apt: pkg=$item state=latest
      with_items:
        - python-software-properties
        - ubuntu-cloud-keyring
        - ntp

      # http://docs.openstack.org/grizzly/openstack-compute/install/apt/content/installing-the-cloud-controller.html
    - name: install cloud archive
      apt_repository: repo="deb http://ubuntu-cloud.archive.canonical.com/ubuntu precise-updates/grizzly main"

    - name: install gplhost grizzly archive
      apt_repository: repo="deb http://archive.gplhost.com/debian grizzly main"

    - name: install gplhost grizzly-backports archive
      apt_repository: repo="deb http://archive.gplhost.com/debian grizzly-backports main"

    - name: install gplhost precise-grizzly-backports archive
      apt_repository: repo="deb http://archive.gplhost.com/debian precise-grizzly-backports main"

    - name: update apt cache
      apt: update_cache=yes force=yes

    - name: ensure gplhost-archive-keyring is present
      apt: pkg=gplhost-archive-keyring state=latest force=yes

    - name: update the cache
      apt: update_cache=yes

    # reboot from ansible?
    # - name: upgrade software packages to latest version
    #  apt: upgrade=dist update_cache=yes

    - name: autoremove unneeded packages
      command: apt-get -y autoremove

    # FIXME: proper setup of ntp on nodes
    - name: update ntp.conf file for server
      template: src=templates/etc/ntp.conf dest=/etc/ntp.conf owner=root group=root mode=0644
      notify: restart ntp

  handlers:
  - name: restart ntp
    service: name=ntp state=restarted

# FIXME: this is not quite right
- name: set up ntpdate client on compute nodes to sync with server
  hosts: compute
  sudo: True
  gather_facts: False
  tasks:
    - name: install ntpdate daily cron job
      template: src=templates/etc/cron.daily/ntpdate dest=/etc/cron.daily/ntpdate owner=root group=root mode=0755
      tags: ntp

- name: MySQL setup
  hosts: controller
  sudo: True
  tasks:

    - name: disable net.ipv4.conf.all.rp_filter in sysctl
      sysctl: name=net.ipv4.conf.all.rp_filter value=0 state=present 

    - name: disable net.ipv4.conf.default.rp_filter in sysctl
      sysctl: name=net.ipv4.conf.default.rp_filter value=0 state=present 

    - name: install mysql and python mysql client
      apt: pkg=$item state=latest
      with_items:
        - python-mysqldb
        - mysql-server

    - name: mysql config file that binds to all interfaces
      copy: src=files/etc/my.cnf dest=/etc/mysql/my.cnf owner=root group=root mode=0644
      notify: restart mysql

    - name: update mysql root password for all root accounts
      mysql_user: name=root host=localhost password=$root_db_password

    # Need to do this for idempotency, see
    # http://ansible.cc/docs/modules.html#mysql-user
    - name: copy .my.cnf file with root password credentials
      template: src=templates/root/.my.cnf dest=/root/.my.cnf owner=root mode=0600

    - name: update mysql root password for all root accounts
      mysql_user: name=root host=$item password=$root_db_password
      with_items:
        - $ansible_hostname
        - 127.0.0.1
        - ::1

    - name: ensure anonymous users are not in the database
      mysql_user: name='' host=$item state=absent
      with_items:
        - localhost
        - $inventory_hostname

    - name: install rabbitmq server
      apt: pkg=rabbitmq-server state=latest

  handlers:
    - name: restart mysql
      service: name=mysql state=restarted
