---
- name: Setup steps that are not specific to a particular OpenStack project
  hosts: all
  sudo: True
  gather_facts: False
  tasks:

    - name: update apt cache
      apt: update_cache=yes

    - name: ensure required base packages are present
      apt: pkg="$item" state=latest
      with_items:
        - python-mysqldb
        - python-software-properties
        - ubuntu-cloud-keyring

    - name: ensure needed repositories are present
      apt_repository: repo="$item" state=present
      with_items:
        - deb http://ubuntu-cloud.archive.canonical.com/ubuntu precise-updates/grizzly main
        - deb http://archive.gplhost.com/debian grizzly main
        - deb http://archive.gplhost.com/debian grizzly-backports main
        - deb http://archive.gplhost.com/debian precise-grizzly-backports main

    - name: update apt cache
      apt: update_cache=yes force=yes

    - name: ensure gplhost-archive-keyring is present
      apt: pkg=gplhost-archive-keyring state=latest force=yes

    - name: upgrade software packages to latest version
      apt: upgrade=dist update_cache=yes

    - name: autoremove unneeded packages
      command: apt-get -y autoremove

    # FIXME: better automation, at least only reboot if kernel is upgraded.
    - name: reboot since there may have been a kernel upgrade
      command: /sbin/reboot

    - name: wait for reboot
      pause: prompt="Wait for all servers to reboot, then press [Enter]" 


- name: MySQL setup
  hosts: mysql
  sudo: True
  tasks:

    - name: ensure mysql-server is installed
      apt: pkg=mysql-server state=latest

    - name: stop mysql
      service: name=mysql state=stopped

    - name: mysql config file that binds to all interfaces
      template: src=common/etc/my.cnf dest=/etc/mysql/my.cnf owner=root group=root mode=0644


    - name: start mysql
      service: name=mysql state=started

    # Need to do this for idempotency, see
    # http://ansible.cc/docs/modules.html#mysql-user
    - name: update mysql root password for all root accounts
      mysql_user: name=root host=localhost password="$mysql_root_password"

    - name: copy .my.cnf file with root password credentials
      template: src=common/root/.my.cnf dest=/root/.my.cnf owner=root group=root mode=0600

    # 'localhost' needs to be the last item for idempotency, see
    # http://ansible.cc/docs/modules.html#mysql-user
    - name: update mysql root password for all root accounts
      mysql_user: name=root host=$item password="$mysql_root_password" priv=*.*:ALL,GRANT
      with_items:
        - $ansible_hostname
        - 127.0.0.1
        - ::1

    - name: ensure anonymous users are not in the database
      mysql_user: name='' host=$item state=absent
      with_items:
        - localhost
        - $inventory_hostname


- name: RabbitMQ setup
  hosts: rabbitmq
  sudo: True
  tasks:

    - name: ensure rabbitmq server is installed
      apt: pkg=rabbitmq-server state=latest

    - name: ensure anonymous guest user is absent
      rabbitmq_user: user=guest state=absent

    - name: ensure openstack vhost is present
      rabbitmq_vhost: name=/openstack state=present
    - name: ensure openstack user is present
      rabbitmq_user: user=openstack password="$rabbitmq_password" vhost=/openstack state=present
