---
- name: Setup steps that are not specific to a particular OpenStack project
  hosts: cloud
  user: vagrant
  sudo: True
  gather_facts: False
  tasks:

      # This is necessary to use the apt_repository module
    - name: ensure add-apt-repository is present
      apt: pkg=python-software-properties update_cache=yes

      # http://docs.openstack.org/folsom/openstack-compute/install/apt/content/installing-the-cloud-controller.html
    - name: install cloud archive
      apt_repository: repo="deb http://ubuntu-cloud.archive.canonical.com/ubuntu precise-updates/folsom main"

      # http://docs.openstack.org/folsom/openstack-compute/install/apt/content/installing-ntp.html
    - name: install ubuntu cloud keyring and ntp
      apt: pkg=$item update_cache=yes
      with_items:
        - ubuntu-cloud-keyring
        - ntp

    - name: update ntp.conf file for server
      action: copy src=files/etc/ntp.conf dest=/etc/ntp.conf owner=root group=root mode=0644
      notify: restart ntp

  handlers:
  - name: restart ntp
    service: name=ntp state=restarted
