---
- name: Setup steps that are not specific to a particular OpenStack project
  hosts: cloud
  sudo: True
  gather_facts: False
  tasks:

      # This is necessary to use the apt_repository module
    - name: ensure add-apt-repository is present
      apt: pkg=python-software-properties update_cache=yes

      # http://docs.openstack.org/folsom/openstack-compute/install/apt/content/installing-the-cloud-controller.html
    - name: install cloud archive
      apt_repository: repo="deb http://ubuntu-cloud.archive.canonical.com/ubuntu precise-updates/folsom main"

      # http://docs.openstack.org/folsom/openstack-compute/install/apt/content/installing-ntp.html
    - name: install ubuntu cloud keyring and ntp
      apt: pkg=$item update_cache=yes
      with_items:
        - ubuntu-cloud-keyring
        - ntp

    - name: update ntp.conf file for server
      action: copy src=files/etc/ntp.conf dest=/etc/ntp.conf owner=root group=root mode=0644
      notify: restart ntp

  handlers:
  - name: restart ntp
    service: name=ntp state=restarted

- name: set up ntpdate client on compute nodes to sync with server
  hosts: compute
  sudo: True
  gather_facts: False
  tasks:
    - name: install ntpdate daily cron job
      template: src=templates/etc/cron.daily/ntpdate dest=/etc/cron.daily/ntpdate owner=root group=root mode=0755
      tags: ntp

- name: MySQL setup
  hosts: controller
  sudo: True
  tasks:
    - name: install mysql and python mysql client
      apt: pkg=$item
      with_items:
        - python-mysqldb
        - mysql-server

    - name: update mysql root password for all root accounts
      mysql_user: name=root host=localhost password=$root_db_password

    # Need to do this for idempotency, see
    # http://ansible.cc/docs/modules.html#mysql-user
    - name: copy .my.cnf file with root password credentials
      template: src=templates/root/.my.cnf dest=/root/.my.cnf owner=root mode=0600

    - name: update mysql root password for all root accounts
      mysql_user: name=root host=localhost password=$root_db_password
      with_items:
        - $ansible_hostname
        - 127.0.0.1
        - ::1

    - name: ensure anonymous users are not in the database
      mysql_user: name='' host=$item state=absent
      with_items:
        - localhost
        - $inventory_hostname
