---
- name: Set up compute node
  hosts: compute
  sudo: True

  tasks:

  - name: disable net.ipv4.conf.all.rp_filter in sysctl
    sysctl: name=net.ipv4.conf.all.rp_filter value=0 state=present

  - name: disable net.ipv4.conf.default.rp_filter in sysctl
    sysctl: name=net.ipv4.conf.default.rp_filter value=0 state=present

  # http://docs.openstack.org/folsom/openstack-compute/install/apt/content/installing-additional-compute-nodes.html
  - name: ensure nova-compute packages are installed
    apt: pkg=$item update-cache=yes
    with_items:
      - python-mysqldb
      - nova-compute-qemu
      - build-essential
      - dkms
      - openvswitch-common
      - openvswitch-datapath-dkms
      - openvswitch-datapath-source
      - openvswitch-switch
      - quantum-plugin-openvswitch-agent
      
  - name: ensure services are stopped
    service: name=$item state=stopped
    with_items:
      - nova-compute
      - quantum-plugin-openvswitch-agent

  - name: ensure OVS kernel module is loaded
    action: command /sbin/modprobe openvswitch_mod
    register: modprobe_result
    ignore_errors: True

  - name: build openvswitch-datapath kernel module - this may take a while
    action: command /usr/bin/module-assistant -i auto-install openvswitch-datapath
    only_if: "'${modprobe_result.stderr}'.find('FATAL: Module openvswitch_mod not found.') == 0"

  - name: ensure openvswitch-switch is started
    service: name=openvswitch-switch state=started

  - name: ensure ovs bridge for gateway br-ex present
    command: /usr/bin/ovs-vsctl -- --may-exist add-br br-int

  - name: ensure nova.conf file is present
    template: src=templates/etc/nova/nova.conf dest=/etc/nova/nova.conf owner=nova group=nova mode=0600

  - name: update api-paste.ini from template
    template: src=templates/etc/nova/api-paste.ini dest=/etc/nova/api-paste.ini owner=nova group=nova mode=0600

  # FIXME: check
  - name: ensure quantum sqlite is deleted
    file: dest=/var/lib/quantum/quantum.sqlite state=absent

  # http://docs.openstack.org/folsom/openstack-compute/install/apt/content/compute-minimum-configuration-settings.html
  - name: update quantum.conf from template
    template: src=templates/etc/quantum/quantum.conf dest=/etc/quantum/quantum.conf owner=quantum group=quantum mode=0600

  - name: update ovs_quantum_plugin.ini from template
    template: src=templates/etc/quantum/plugins/openvswitch/ovs_quantum_plugin.ini dest=/etc/quantum/plugins/openvswitch/ovs_quantum_plugin.ini owner=quantum group=quantum mode=0600

  - name: make sure symlink to ovs_quantum_plugin.ini exists
    file: src=/etc/quantum/plugins/openvswitch/ovs_quantum_plugin.ini dest=/etc/quantum/plugin.ini state=link

  - name: ensure services are started
    service: name=$item state=started
    with_items:
      - nova-compute
      - quantum-plugin-openvswitch-agent
