---
- hosts: controller
  sudo: True
  gather_facts: False

  tasks:

    # http://docs.openstack.org/essex/openstack-compute/install/apt/content/install-glance.html
  - name: ensure glance is installed
    apt: pkg=glance state=latest

  - name: ensure glance service are stopped
    service: name=$item state=stopped
    with_items:
      - glance-registry
      - glance-api

    # http://docs.openstack.org/essex/openstack-compute/install/apt/content/configure-glance-mysql.html
  - name: ensure glance database is present
    mysql_db: name=glance

  - name: ensure glance database user is present
    mysql_user: name=glance host=$item password=${glance_db_password} priv=glance.*:ALL
    with_items:
      - '%'
      - localhost

  - name: ensure glance sqlite is deleted
    file: dest=/var/lib/glance/glance.sqlite state=absent

  # http://docs.openstack.org/folsom/openstack-compute/install/apt/content/configure-glance-files.html
  - name: update glance-api.conf file from template
    template: src=templates/etc/glance/glance-api.conf dest=/etc/glance/glance-api.conf owner=glance group=glance mode=0600

  - name: update glance-registry.conf file from template
    template: src=templates/etc/glance/glance-registry.conf dest=/etc/glance/glance-registry.conf owner=glance group=glance mode=0600

  - name: ensure database is synced
    glance_manage: action=dbsync

  - name: ensure services are started
    service: name=$item state=started
    with_items:
      - glance-registry
      - glance-api

  # http://docs.openstack.org/folsom/openstack-compute/install/apt/content/images-verifying-install.html
- hosts: controller
  gather_facts: False
  vars:
    imgfile: cirros-0.3.1-x86_64-disk.img
    cirros_url: http://download.cirros-cloud.net/0.3.1/$imgfile

  tasks:
  - name: ensure temporary image directory exists
    file: dest=/tmp/images state=directory

  - name: ensure test image has been obtained
    get_url: url=$cirros_url dest=/tmp/images/$imgfile

  - name: add cirros image
    glance: name=cirros-0.3.1-x86_64 file=/tmp/images/$imgfile disk_format=qcow2 is_public=true user=admin tenant=demo password=secrete region=RegionOne auth_url=http://10.10.10.10:5000/v2.0
