---
- hosts: controller
  sudo: True
  vars:
    admin_token: 012345SECRET99TOKEN012345
    service_users:
      - glance
      - nova
      - ec2
      - swift
  tags:
    - keystone

  tasks:
  # http://docs.openstack.org/folsom/openstack-compute/install/apt/content/install-keystone.html
  - name: ensure keystone package is installed
    apt: pkg=keystone

  - name: ensure sqlite keystone database is deleted
    file: dest=/var/lib/keystone/keystone.db state=absent

  - name: ensure keystone database is present
    mysql_db: name=keystone

  - name: ensure keystone database user is present
    mysql_user: name=keystone host=% password=${keystone_db_password} priv=keystone.*:ALL

  - name: ensure keystone config script is present
    template: src=templates/etc/keystone/keystone.conf dest=/etc/keystone/keystone.conf owner=keystone group=keystone mode=0600
    notify: restart keystone

  - name: initialize keystone database
    keystone_manage: action=db_sync
    notify: restart keystone

    # http://docs.openstack.org/folsom/openstack-compute/install/apt/content/setting-up-tenants-users-and-roles-manually.html
    # Same as keystone tenant-craete
  - name: create default tenant
    keystone_user: token=$admin_token tenant=demo tenant_description="Default Tenant"

    # Same as keystone user-create
  - name: create admin user
    keystone_user: token=$admin_token user=admin tenant=demo password=secrete

    # Same as keystone role-create and keystone user-role-add
  - name: create admin role and associate it with admin user
    keystone_user: token=$admin_token role=admin user=admin tenant=demo

  - name: create service tenant
    keystone_user: token=$admin_token tenant=service tenant_description="Service Tenant"

  - name: create users for each of the services
    keystone_user: token=$admin_token user=$item tenant=service password=$item
    with_items: $service_users

  - name: add each of the service users to the service tenant with the admin role
    keystone_user: token=$admin_token role=admin user=$item tenant=service
    with_items: $service_users


  handlers:
   - name: restart keystone
     service: name=keystone state=restarted
