---
- name: Set up compute node
  hosts: compute
  sudo: True

  tasks:
  # http://www.mirantis.com/blog/openstack-networking-single-host-flatdhcpmanager/
  - name: ensure eth2 is in promiscuous mode
    action: command /sbin/ip link set eth2 promisc on

  # http://docs.openstack.org/folsom/openstack-compute/install/apt/content/installing-additional-compute-nodes.html
  - name: ensure nova-compute packages are installed
    apt: pkg=$item update-cache=yes
    with_items:
      - python-mysqldb
      - nova-compute-qemu
      - bridge-utils
      - guestmount

  - name: ensure libguest has been updated
    command: /usr/sbin/update-guestfs-appliance

  - name: ensure nova.conf file is present
    template: src=templates/etc/nova/nova.conf dest=/etc/nova/nova.conf owner=nova group=nova mode=0600
    notify:
      - restart nova-compute
    tags: debug

  - name: ensure api-paste.ini is present
    copy: src=files/etc/nova/api-paste.ini dest=/etc/nova/api-paste.ini owner=nova group=nova mode=0600
    notify:
      - restart nova-compute

  handlers:
  - name: restart nova-compute
    service: name=nova-compute state=restarted
