---
- name: Set up compute node
  hosts: compute
  sudo: True

  tasks:
  # http://docs.openstack.org/folsom/openstack-compute/install/apt/content/installing-additional-compute-nodes.html
  - name: ensure nova-compute packages are installed
    apt: pkg=$item update-cache=yes
    with_items:
      - python-mysqldb
      - nova-compute-qemu
      - nova-network
      - bridge-utils

  - name: ensure nova.conf file is present
    template: src=templates/etc/nova/nova.conf dest=/etc/nova/nova.conf owner=nova group=nova mode=0600
    notify:
      - restart nova-compute
    tags: debug

  - name: ensure api-paste.ini is present
    copy: src=files/etc/nova/api-paste.ini dest=/etc/nova/api-paste.ini owner=nova group=nova mode=0600
    notify:
      - restart nova-compute

  handlers:
  - name: restart nova-compute
    service: name=nova-compute state=restarted
