---
- hosts: controller
  sudo: True
  tasks:

  - name: ensure nova database is present
    mysql_db: name=nova

  # http://docs.openstack.org/folsom/openstack-compute/install/apt/content/setting-up-sql-database-mysql.html
  - name: ensure nova database user is present
    mysql_user: name=nova host=$item password=$nova_db_password priv=nova.*:ALL
    with_items:
      - '%'
      - localhost

    # http://docs.openstack.org/folsom/openstack-compute/install/apt/content/installing-the-cloud-controller.html
  - name: ensure nova packages are installed
    apt: pkg=$item state=latest
    with_items:
      - nova-api
      - nova-cert
      - nova-common
      - nova-conductor
      - nova-scheduler
      - python-nova
      - python-novaclient
      - nova-consoleauth
      - novnc
      - nova-novncproxy

  - name: ensure services are stopped
    service: name=$item state=stopped
    with_items:
      - nova-api
      - nova-cert
      - nova-conductor
      - nova-consoleauth
      - nova-scheduler
      - nova-novncproxy

  - name: ensure api-paste.ini is present
    template: src=templates/etc/nova/api-paste.ini dest=/etc/nova/api-paste.ini owner=nova group=nova mode=0600

  # http://docs.openstack.org/folsom/openstack-compute/install/apt/content/compute-minimum-configuration-settings.html
  - name: ensure nova.conf file is present
    template: src=templates/etc/nova/nova.conf dest=/etc/nova/nova.conf owner=nova group=nova mode=0600

  # http://docs.openstack.org/folsom/openstack-compute/install/apt/content/compute-db-sync.html
  - name: ensure database is synced
    command: /usr/bin/nova-manage db sync

  - name: ensure services are started
    service: name=$item state=started
    with_items:
      - nova-api
      - nova-cert
      - nova-conductor
      - nova-consoleauth
      - nova-scheduler
      - nova-novncproxy

