---
- hosts: controller
  user: vagrant
  sudo: True
  gather_facts: False
  vars_files:
    - ../global_vars.yaml
  vars:
    glance_db_password: ataglance

  tasks:
    # http://docs.openstack.org/essex/openstack-compute/install/apt/content/install-glance.html
  - name: ensure glance is installed
    action: apt pkg=glance
  - name: ensure glance sqlite is deleted
    action: file dest=/var/lib/glance/glance.sqlite state=absent

    # http://docs.openstack.org/essex/openstack-compute/install/apt/content/configure-glance-mysql.html
  - name: ensure create glance sql script is present
    action: template src=templates/create-glance-db.sql dest=/tmp/create-glance-db.sql owner=root group=root mode=0600
  - name: ensure glance sql script is executed
    action: shell mysql -u root < /tmp/create-glance-db.sql

  # http://docs.openstack.org/essex/openstack-compute/install/apt/content/configure-glance-files.html
  - name: ensure glance-api-paste.ini file is up to date
    action: file src=files/glance-api-paste.ini dest=/etc/glance/glance-api-paste.ini owner=glance group=glance mode=0644
  - name: ensure glance-api is restarted
    action: service name=glance-api state=restarted
  - name: ensure glance-registry.conf file is up to date
    action: template src=templates/glance-registry.conf dest=/etc/glance/glance-registry.conf owner=glance group=glance mode=0644
  - name: ensure glance-registry-paste.ini file is up to date
    action: file src=files/glance-registry-paste.ini dest=/etc/glance/glance-registry-paste.ini owner=glance group=glance mode=0644
  - name: ensure glance database is populated
    action: command glance-manage db_sync
  - name: ensure glance-registry is restarted
    action: service name=glance-registry state=restarted
  - name: ensure glance-api is restarted
    action: service name=glance-api state=restarted
