---
- hosts: controller
  user: vagrant
  sudo: True
  gather_facts: False
  vars_files:
    - ../global_vars.yaml

  tasks:
    # http://docs.openstack.org/essex/openstack-compute/install/apt/content/install-glance.html
  - name: ensure glance is installed
    action: apt pkg=glance

  - name: ensure glance sqlite is deleted
    action: file dest=/var/lib/glance/glance.sqlite state=absent

    # http://docs.openstack.org/essex/openstack-compute/install/apt/content/configure-glance-mysql.html
  - name: ensure glance database is present
    action: mysql_db name=glance
    notify:
      - version glance database
      - populate glance database

  - name: ensure glance database user is present
    action: mysql_user name=glance host=% password=${glance_db_password} priv=glance.*:ALL

  # http://docs.openstack.org/essex/openstack-compute/install/apt/content/configure-glance-files.html
  - name: ensure glance-api-paste.ini file is up to date
    action: copy src=files/glance-api-paste.ini dest=/etc/glance/glance-api-paste.ini owner=glance group=glance mode=0644

  - name: ensure glance-api.conf file is up to date
    action:  copy src=files/glance-api.conf dest=/etc/glance/glance-api.conf owner=glance group=glance mode=0644

  - name: ensure glance-registry.conf file is up to date
    action: template src=templates/glance-registry.conf dest=/etc/glance/glance-registry.conf owner=glance group=glance mode=0644

  - name: ensure glance-registry-paste.ini file is up to date
    action: copy src=files/glance-registry-paste.ini dest=/etc/glance/glance-registry-paste.ini owner=glance group=glance mode=0644

  - name: restart glance-registry
    action: service name=glance-registry state=restarted

  - name: restart glance-api
    action: service name=glance-api state=restarted

  handlers:
  - name: version glance database
    action: command glance-manage version_control 0

  - name: populate glance database
    action: command glance-manage db_sync


  # http://docs.openstack.org/essex/openstack-compute/install/apt/content/images-verifying-install.html
- hosts: controller
  user: vagrant
  gather_facts: False
  tags:
    - image

  tasks:
  - name: ensure temporary image directory exists
    action: file dest=/tmp/images state=directory

  - name: ensure test image has been obtained
    action: get_url url=https://launchpad.net/cirros/trunk/0.3.0/+download/cirros-0.3.0-x86_64-disk.img dest=/tmp/images/cirros.img

  - name: ensure openrc file has been copied
    action: copy src=../openrc dest=/home/vagrant/openrc

  - name: ensure image has been added to glance
    action: shell /usr/bin/glance --os_username=adminUser --os_password=secretword --os_tenant=openstackDemo --os_auth_url=http://127.0.0.1:5000/v2.0 add name=cirros-0.3.0-x86_64 disk_format=qcow2 container_format=bare < /tmp/images/cirros.img