---
- name: RabbitMQ setup
  hosts: rabbitmq
  sudo: True
  tasks:

    - name: ensure rabbitmq server is installed
      apt: pkg=rabbitmq-server state=latest

    - name: ensure anonymous guest user is absent
      rabbitmq_user: user=guest state=absent

    - name: ensure openstack vhost is present
      rabbitmq_vhost: name=/openstack state=present

    - name: ensure openstack user is present
      rabbitmq_user: user=openstack 
                     password="$rabbitmq_password" 
                     vhost=/openstack 
                     configure_priv=.*
                     read_priv=.*
                     write_priv=.*
                     state=present
